// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drmismwbcohktquctoal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybWlzbXdiY29oa3RxdWN0b2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMDkyNTksImV4cCI6MjA3MTU4NTI1OX0.u6MuoodnZfLMSVcjWwa9V1OzTwMmR87dxBXV-7sODTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});